package parse

import (
	"bytes"
	"path"
	"regexp"
	"strings"
	"time"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"

	"github.com/curiousjc/coroner/internal/doc"
)

// htmlsiteParser reads a hand-built HTML site: one page per post, written and
// maintained by hand rather than generated by a platform.
//
// It is a separate format from `html` rather than a configuration of it, and the
// reason is the title. The generic parser falls back to the <title> element, and
// on this site 188 of 189 pages carry the identical site banner there. Since
// doc.Indexed prepends the title to every chunk before embedding, taking <title>
// would inject the same string into every vector in the corpus and flatten
// exactly the distinctions search exists to find -- the same failure the Facebook
// export's `title` field presented, arriving by a different route. Here the real
// title is the <h1>, and the site's structure is known well enough to say so
// rather than guess.
//
// Everything below was measured against the real 189-page export. Re-measure
// before simplifying any of it.
type htmlsiteParser struct{}

// Include is HTML only. The site has no sidecar and no other file types worth
// reading, so the narrow glob is also the complete one.
func (p *htmlsiteParser) Include() []string {
	return []string{"*.html", "*.htm"}
}

// Prepare has nothing to do: every page carries its own metadata, which is the
// whole difference between this format and Substack's.
func (p *htmlsiteParser) Prepare(src Source) error { return nil }

func (p *htmlsiteParser) ParseFile(src Source, rel string, data []byte) ([]doc.Document, error) {
	root, err := html.Parse(bytes.NewReader(data))
	if err != nil {
		// html.Parse is extremely forgiving and essentially only fails on I/O,
		// but a file it cannot handle is a file we must not silently drop.
		return nil, err
	}

	body := contentRoot(root)
	if body == nil {
		return nil, nil
	}

	// The first <h1> is the title and the first <h2> is the date line. Measured:
	// exactly one of each on 186 of 189 pages, none on the other three, and no
	// page uses either as a subheading further down. That is what makes removing
	// them from the body text safe -- on a site where <h2> were a real
	// subheading, this would be destroying writing.
	h1 := firstElement(body, atom.H1)
	h2 := firstElement(body, atom.H2)

	title := ""
	if h1 != nil {
		title = strings.TrimSpace(textOf(h1))
	}
	if strings.EqualFold(title, "title") {
		// Five pages were started from a template and never had the heading
		// filled in. The literal word is not a title, and letting it through
		// would give five unrelated posts the same one.
		title = ""
	}
	if title == "" {
		title = titleFromSlug(rel)
	}

	// The <h2> is only treated as the date line -- and so removed from the body
	// -- when it actually parses as a date. On the three pages whose <h2> holds
	// something else, that something else is writing and is kept.
	dateLine := h2
	if dateLine != nil && parseSiteDate(textOf(dateLine)).IsZero() {
		dateLine = nil
	}

	d := doc.New(src.Name, src.Type, rel, rel, doc.Document{
		Title:     title,
		Author:    src.Author,
		Published: siteDate(rel, dateLine),
		Text:      extractSiteText(body, h1, dateLine),
	})

	if d.Text == "" {
		return nil, nil
	}
	return []doc.Document{d}, nil
}

// datePrefix matches the date every page's filename begins with. Both separators
// appear (168 pages use "-", 11 use "."), and ten pages leave off a leading zero
// on the month or the day, so neither the separator nor the width can be fixed.
var datePrefix = regexp.MustCompile(`^(\d{4})[.\-_](\d{1,2})[.\-_](\d{1,2})[.\-_]*`)

// siteDate resolves a page's publication date.
//
// The filename wins, always. Both sources were cross-checked across the whole
// export: they agree on 169 pages and disagree on 14, and every disagreement is
// the <h2> being wrong. Four pages carry 10.25.2016 -- the date of the very
// first post, whose page was clearly used as a template -- one carries a year
// typo'd a decade out, and the rest are off by a day or two. Six pages have no
// <h2> date at all, while all 189 have a filename date.
//
// So the <h2> is not a fallback and is not consulted here. A wrong date is worse
// than no date, because it silently reorders everything sorted by recency, and a
// source that is wrong 14 times out of 183 is not one to reach for when the
// reliable one is already complete.
func siteDate(rel string, dateLine *html.Node) time.Time {
	if t := dateFromFilename(rel); !t.IsZero() {
		return t
	}
	// Only reached if a page is ever added without a dated filename. The <h2> is
	// worth more than nothing, and this is the one situation where it cannot
	// contradict a better source.
	if dateLine != nil {
		return parseSiteDate(textOf(dateLine))
	}
	return time.Time{}
}

func dateFromFilename(rel string) time.Time {
	m := datePrefix.FindStringSubmatch(path.Base(rel))
	if m == nil {
		return time.Time{}
	}
	t, err := time.Parse("2006-1-2", m[1]+"-"+m[2]+"-"+m[3])
	if err != nil {
		return time.Time{}
	}
	return t.UTC()
}

// siteDateLayouts covers the four shapes the <h2> line uses: 175 pages are
// MM.DD.YYYY, five are MM.D.YYYY, two are M.DD.YYYY and one is MM-DD-YYYY. Go's
// "1" and "2" verbs accept a leading zero as well as its absence, so two layouts
// cover all four.
var siteDateLayouts = []string{"1.2.2006", "1-2-2006"}

func parseSiteDate(s string) time.Time {
	s = strings.TrimSpace(s)
	if s == "" {
		return time.Time{}
	}
	for _, layout := range siteDateLayouts {
		if t, err := time.Parse(layout, s); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

// titleFromSlug builds a title from the filename for the pages that have no
// usable <h1>, stripping the date prefix first so the title does not begin with
// a number that is already carried as the publication date.
//
// The " copy" suffix six pages carry is also dropped. Those are not duplicates
// -- each was checked and none has a surviving twin -- so the pages stay; it is
// only the filename that records an editing accident, and it should not become
// part of a title.
func titleFromSlug(rel string) string {
	base := path.Base(rel)
	if i := strings.LastIndex(base, "."); i > 0 {
		base = base[:i]
	}

	base = datePrefix.ReplaceAllString(base, "")
	base = strings.NewReplacer("_", " ", "-", " ").Replace(base)
	base = strings.TrimSpace(strings.Join(strings.Fields(base), " "))

	if trimmed := strings.TrimSuffix(base, " copy"); trimmed != "" {
		base = trimmed
	}
	return base
}

// extractSiteText renders the page body as text, minus the title and date
// headings, and with the markup's line wrapping undone.
//
// The unwrapping is the part that matters. HTML treats a newline as ordinary
// whitespace, so a browser renders a hand-wrapped paragraph as one continuous
// line -- but doc.Normalise deliberately preserves newlines, because for most
// formats they are authored structure. Passing the markup's wrapping through
// would put a hard break every eighty characters inside the resulting text,
// which reads badly in a snippet and gives the chunker false boundaries.
//
// Blank lines are kept, and that is a departure from what a browser would do.
// Twenty-three of these pages have no <p> tags at all -- the writing sits
// directly in the container div -- and in about half of those the author's only
// record of where the paragraphs fall is a blank line. HTML says to ignore it;
// the file says it was meant. Since the chunker splits on paragraph boundaries,
// honouring it recovers structure that would otherwise be lost, and on the pages
// that do use <p> it changes nothing.
func extractSiteText(root, title, dateLine *html.Node) string {
	var b strings.Builder
	walkSiteText(root, title, dateLine, &b)
	return doc.Normalise(b.String())
}

func walkSiteText(n, title, dateLine *html.Node, b *strings.Builder) {
	if n == nil || (title != nil && n == title) || (dateLine != nil && n == dateLine) {
		return
	}

	switch n.Type {
	case html.TextNode:
		b.WriteString(unwrap(n.Data))
		return
	case html.CommentNode, html.DoctypeNode:
		return
	case html.ElementNode:
		if skipped[n.DataAtom] {
			return
		}
	}

	block := n.Type == html.ElementNode && blocks[n.DataAtom]
	if block {
		b.WriteString("\n\n")
	}

	for c := n.FirstChild; c != nil; c = c.NextSibling {
		walkSiteText(c, title, dateLine, b)
	}

	if block {
		b.WriteString("\n\n")
	}
}

// unwrap collapses each run of whitespace to a single space, except a run
// carrying more than one newline, which becomes a paragraph break.
//
// Byte-wise rather than rune-wise on purpose: every byte it tests for is ASCII,
// and in UTF-8 no byte of a multi-byte character can be mistaken for one, so
// non-ASCII text is copied through untouched.
func unwrap(s string) string {
	var b strings.Builder
	b.Grow(len(s))

	for i := 0; i < len(s); {
		if !isASCIISpace(s[i]) {
			b.WriteByte(s[i])
			i++
			continue
		}

		newlines := 0
		for i < len(s) && isASCIISpace(s[i]) {
			if s[i] == '\n' {
				newlines++
			}
			i++
		}

		if newlines > 1 {
			b.WriteString("\n\n")
		} else {
			b.WriteByte(' ')
		}
	}

	return b.String()
}

func isASCIISpace(c byte) bool {
	return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\v' || c == '\f'
}
